name: covid_app
description: A new Flutter project.

publish_to: 'none'


environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  dio:
  logger:
  connectivity_plus:
  equatable:
  flutter_svg:
  permission_handler:
  mockito:
  bloc_test:
  fl_chart:
  json_serializable:
  json_annotation:
  http_status_code:
  auto_size_text:
  flutter_spinkit:
  intl:
  geolocator:
  geocode:
  flutter_typeahead:


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/icons/